### ISSUE TITLE
PeliasGeocoding plugin cannot be loaded with upgrade to QGIS 3.18 "Zurich"

### ISSUE THREAD

**Issue by stevevance** [nilsnolde/pelias-qgis-plugin#7]
I downloaded and ran QGIS 3.18 "Zurich" today and it reported that it cannot load PeliasGeocoding plugin. 

<img width="848" alt="image" src="https://user-images.githubusercontent.com/1330459/112784710-f8ef1e00-9017-11eb-98d8-20306aacd439.png">

````
Couldn't load plugin 'PeliasGeocoding' 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 145: ordinal not in range(128) 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 313, in loadPlugin
    __import__(packageName)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/stevevance/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/PeliasGeocoding/__init__.py", line 54, in 
    METADATA.read(os.path.join(BASE_DIR, 'metadata.txt'))
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 145: ordinal not in range(128)


Python version: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
QGIS version: 3.18.1-Zürich Zürich, 202f1bf7e5 

Python Path:
/Users/stevevance/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/networks
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/stevevance/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/stevevance/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/click_plugins-1.1.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/rasterio-1.1.5-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/cftime-1.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/pyproj-2.6.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numpy-1.20.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/patsy-0.5.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/statsmodels-0.11.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/affine-2.3.0-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/snuggs-1.4.7-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/GDAL-3.2.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/geopandas-0.8.1-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python38.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/netCDF4-1.5.4-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Fiona-1.8.13.post1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/Rtree-0.9.4-py3.8.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/numba-0.50.1-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/opencv_contrib_python-4.3.0.36-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/pandas-1.1.0-py3.8-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.8/site-packages/scipy-1.5.1-py3.8-macosx-10.13.0-x86_64.egg
/Users/stevevance/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/stevevance/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/ext-libs
/Users/stevevance/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Beeline/libs
/Users/stevevance/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing
/Users/stevevance/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/ext_libs
````

**Comment by nilsnolde** [comment]
Wasn’t sure anyone was using the plugin😅 And didn’t open it myself in ages. I’ll have a quick look later. Though I might deprecate it, too few actual users to justify maintenance.

**Comment by nilsnolde** [comment]
Ok, now I saw the actual error: something weird was introduced in your `metadata.txt` (smth not ascii). I don't have that problem when I installed Pelias. Try a re-install, that should def fix it.

Feel free to open again if not.
